version: '3'
services:
  one:
    build:
      context: ../one
  pipy:
    image: flomesh/pipy:1.0.0
    command: pipy /opt/main.js
    ports:
      - "18080:8000"
    volumes:
      - "./:/opt/"
    depends_on:
      - one
