services:
  one:
    build:
      context: ../one
  sd:
    build:
      context: sd

  gateway:
    image: traefik:v3.1.0
    ports:
      - "8080:80"
    volumes:
      - ./traefik.yml:/traefik.yml
    depends_on:
      - one
