version: '3.7'
services:
  one:
    build:
      context: ../one
  gateway:
    image: traefik:v3.0.0-beta2
    ports:
      - "8080:80"
    volumes:
      - ./confd:/opt/confd
      - ./traefik.yml:/traefik.yml
    depends_on:
      - one
