version: '3'
services:
  one:
    build:
      context: ../one
  lura:
    build:
      context: .
    depends_on:
      - one
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/config.json
