version: '3'
services:
  one:
    build:
      context: ../one
  gateway:
    image: megaease/easegress:v2.3.0
    ports:
      - "10080:10080"
    volumes:
      - ./config:/opt/config
      - ./init.sh:/init.sh
