version: '3'
services:
  one:
    build:
      context: ../one
  gateway:
    image: megaease/easegress:v2.2.0
    ports:
      - "10080:10080"
    volumes:
      - ./config.yml:/opt/config.yml
      - ./pipeline.yml:/opt/pipeline.yml
