version: '3'
services:
  one:
    build:
      context: ../one
  gateway:
    container_name: easegress_gateway
    image: megaease/easegress:v2.3.1
    ports:
      - "10080:10080"
    volumes:
      - ./config:/opt/config
      - ./init.sh:/init.sh
