name: pipeline-demo
kind: Pipeline
flow:
  - filter: proxy
filters:
  - name: requestAdaptor
    kind: RequestAdaptor
    host: one
    path:
    trimPrefix: /one
  - name: proxy
    kind: Proxy
    pools:
    - servers:
      - url: http://one:8080
      loadBalance:
        policy: roundRobin